### ISSUE TITLE
201809ブランチ　Windows10環境　インストール時エラーメッセージ

### ISSUE THREAD

**Issue by tmkawanabe** [SIPupstreamDesign/ChOWDER#40]
windows10環境でインストールしたところ、以下のメッセージが表示されました。
インストール後にChOWDERは起動できました。
それから、インストール時にpythonを要求されました。ドキュメントに記載が必要と思います。
（以下のログはpythonインストール後にChOWDERをインストールしたときのものです）

```
C:¥Users¥tdw¥ChOWDER¥ChOWDER¥bin>install.bat

> uws@9.14.0 install C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> phantomjs-prebuilt@2.1.16 install C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:¥Users¥tdw¥AppData¥Local¥Temp¥phantomjs¥phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥phantomjs-prebuilt¥lib¥phantom
Copying extracted folder C:¥Users¥tdw¥AppData¥Local¥Temp¥phantomjs¥phantomjs-2.1.1-windows.zip-extract-1541479823314¥phantomjs-2.1.1-windows -> C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥phantomjs-prebuilt¥lib¥phantom
Writing location.js file
Done. Phantomjs binary available at C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥phantomjs-prebuilt¥lib¥phantom¥bin¥phantomjs.exe

> hiredis@0.5.0 install C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥hiredis
> node-gyp rebuild


C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥hiredis>if not defined npm_config_node_gyp (node "C:¥Program Files¥nodejs¥node_modules¥npm¥node_modules¥npm-lifecycle¥node-gyp-bin¥¥..¥..¥node_modules¥node-gyp¥bin¥node-gyp.js" rebuild )  else (node "C:¥Program Files¥nodejs¥node_modules¥npm¥node_modules¥node-gyp¥bin¥node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:¥Program Files (x86)¥Python37-32¥python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:¥¥Program Files¥¥nodejs¥¥node.exe" "C:¥¥Program Files¥¥nodejs¥¥node_modules¥¥npm¥¥node_modules¥¥node-gyp¥¥bin¥¥node-gyp.js" "rebuild"
gyp ERR! cwd C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥hiredis
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> images@3.0.1 install C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥images
> node ./scripts/install.js

Cached binary found at C:¥Users¥tdw¥AppData¥Roaming¥npm-cache¥images¥3.0.1¥win32-x64-57_binding.node

> sharp@0.20.5 install C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥sharp¥build¥Release
info sharp Copying DLLs from C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥sharp¥vendor¥lib to C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥sharp¥build¥Release

> websocket@1.0.26 install C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥websocket>if not defined npm_config_node_gyp (node "C:¥Program Files¥nodejs¥node_modules¥npm¥node_modules¥npm-lifecycle¥node-gyp-bin¥¥..¥..¥node_modules¥node-gyp¥bin¥node-gyp.js" rebuild )  else (node "C:¥Program Files¥nodejs¥node_modules¥npm¥node_modules¥node-gyp¥bin¥node-gyp.js" rebuild )

> electron@2.0.10 postinstall C:¥Users¥tdw¥ChOWDER¥ChOWDER¥node_modules¥electron
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: hiredis@0.5.0 (node_modules¥hiredis):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: hiredis@0.5.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 295 packages from 253 contributors and audited 916 packages in 18.095s
found 0 vulnerabilities
```

**Comment by uimac** [comment]
hiredisについては、インストール＆使用できれば、すこし早くなる程度のモジュールで、
windows環境ではインストールに失敗するため、オプションとしております。

pythonはhiredisなどののネイティブモジュールのビルドに使用されますが、
hiredisは上記の通り不要ですし、他のモジュールはビルド済バイナリが落ちてくるはずなので
ChOWDERは, python無しでインストール可能です。

ドキュメントに、hiredis関連のエラーが出ますが使用可能と追記しようかと思います

**Comment by uimac** [comment]
python無しのwindowsでのインストールを行いましたが、問題なく動作しました。
ドキュメントに追記しました
